version: '2.2'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'userDev'
      POSTGRES_PASSWORD: 'userDev'
      POSTGRES_DB: 'TEXTNET'
